import type { Metadata } from "next";
import { TeamContainer } from "@/components/landing/containers/TeamContainer";
import { SectionWrapper, SectionHeading } from "@/components/landing";
import { ShieldCheck, Award, Target } from "lucide-react";

export const metadata: Metadata = {
  title: "About Validra — SIH 2026 Problem Statement 26034",
  description: "About Team VisionMinds, mission, and system design for AI-assisted Legal Metrology enforcement.",
};

export default function AboutPage() {
  return (
    <div className="pt-24 pb-16">
      <SectionWrapper background="hero">
        <SectionHeading
          badge="Smart India Hackathon 2026"
          title="About Validra &"
          highlight="Team VisionMinds"
          subtitle="Revolutionizing packaged commodity regulatory enforcement with deterministic precision and transparent AI."
        />

        <div className="max-w-4xl mx-auto space-y-8 text-slate-700 leading-relaxed text-base sm:text-lg">
          <div className="p-6 sm:p-8 rounded-xl bg-white border border-slate-200 shadow-xs">
            <h3 className="text-xl font-bold text-slate-900 mb-3 flex items-center gap-2.5">
              <Target className="w-5 h-5 text-green-700" />
              The Mission (Problem Statement 26034)
            </h3>
            <p>
              In India, retail consumer protection relies heavily on the{" "}
              <strong className="text-slate-900">Legal Metrology (Packaged Commodities) Rules, 2011</strong>.
              With tens of millions of packaged products entering supply chains, regulatory enforcement
              officers face the monumental challenge of manually verifying tiny declarations like MRP,
              Net Quantity, Date of Manufacture, and Consumer Care details.
            </p>
            <p className="mt-4">
              <strong className="text-green-700">Validra</strong> was conceptualized by Team VisionMinds
              to provide an automated, high-accuracy inspection system that assists inspectors without
              replacing statutory human discretion.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-6 rounded-xl bg-white border border-slate-200 shadow-xs">
              <h4 className="text-lg font-semibold text-slate-900 mb-2 flex items-center gap-2">
                <ShieldCheck className="w-5 h-5 text-green-700" />
                Zero-Hallucination Integrity
              </h4>
              <p className="text-sm text-slate-600">
                Statutory legal decisions must never rely on probabilistic generative AI. Validra couples
                OpenCV and PaddleOCR with mathematical, deterministic rules (C01–C26) so every non-compliance
                is legally explainable.
              </p>
            </div>

            <div className="p-6 rounded-xl bg-white border border-slate-200 shadow-xs">
              <h4 className="text-lg font-semibold text-slate-900 mb-2 flex items-center gap-2">
                <Award className="w-5 h-5 text-green-700" />
                Court-Admissible Evidence
              </h4>
              <p className="text-sm text-slate-600">
                Reports generated by Validra are sealed with cryptographic SHA-256 integrity hashes and
                dynamic QR verification codes, fulfilling Section 65B requirements of the Indian Evidence Act.
              </p>
            </div>
          </div>
        </div>
      </SectionWrapper>

      <TeamContainer />
    </div>
  );
}
