import { SystemInspection } from "@/types/admin";

const MOCK_INSPECTIONS: SystemInspection[] = [
  {
    id: "INS-2026-0842",
    productName: "Premium Basmati Rice 5kg",
    brandName: "Royal Heritage Grains",
    category: "Food & Grains",
    batchNumber: "RHG-2026-B09",
    inspectorId: "usr-02",
    inspectorName: "Rajesh Sharma",
    inspectorEmail: "rajesh.sharma@lm.gov.in",
    status: "COMPLIANT",
    complianceScore: 100,
    violationsCount: 0,
    scannedAt: "2026-09-16 09:42:15",
    reviewedAt: "2026-09-16 09:45:00",
    hashSha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    qrVerified: true,
    findings: [
      {
        id: "f-01",
        ruleCode: "C01",
        field: "Maximum Retail Price (MRP)",
        status: "PASS",
        detectedValue: "₹ 549.00 (Incl. of all taxes)",
        confidenceScore: 0.98,
        severity: "CRITICAL",
        legalRef: "Rule 6(1)(e), PCR 2011",
      },
      {
        id: "f-02",
        ruleCode: "C02",
        field: "Net Quantity",
        status: "PASS",
        detectedValue: "5 kg",
        confidenceScore: 0.99,
        severity: "CRITICAL",
        legalRef: "Rule 12 & 13, PCR 2011",
      },
      {
        id: "f-03",
        ruleCode: "C03",
        field: "Consumer Care Contact",
        status: "PASS",
        detectedValue: "care@royalheritage.in / 1800-200-9988",
        confidenceScore: 0.94,
        severity: "HIGH",
        legalRef: "Rule 6(1)(g), PCR 2011",
      },
    ],
    notes: "All statutory declarations verified against physical bag label and found in strict compliance with PCR 2011.",
  },
  {
    id: "INS-2026-0841",
    productName: "Almond Nourish Shampoo 400ml",
    brandName: "GlowAura Botanicals",
    category: "Cosmetics & Personal Care",
    batchNumber: "GLW-26-881",
    inspectorId: "usr-03",
    inspectorName: "Sunita Deshmukh",
    inspectorEmail: "sunita.deshmukh@lm.gov.in",
    status: "NON_COMPLIANT",
    complianceScore: 68,
    violationsCount: 2,
    scannedAt: "2026-09-16 08:31:00",
    reviewedAt: "2026-09-16 08:36:20",
    hashSha256: "7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069",
    qrVerified: true,
    findings: [
      {
        id: "f-04",
        ruleCode: "C01",
        field: "Maximum Retail Price (MRP)",
        status: "FAIL",
        detectedValue: "MRP ₹ 380",
        confidenceScore: 0.92,
        severity: "CRITICAL",
        legalRef: "Rule 6(1)(e), PCR 2011",
        officerRemarks: "Missing mandatory statutory clause 'inclusive of all taxes'.",
      },
      {
        id: "f-05",
        ruleCode: "C02",
        field: "Net Quantity",
        status: "FAIL",
        detectedValue: "400 mls",
        confidenceScore: 0.89,
        severity: "HIGH",
        legalRef: "Rule 13, PCR 2011",
        officerRemarks: "Used non-standard unit 'mls' instead of statutory 'ml' or 'mL'.",
      },
    ],
    notes: "High severity non-compliance notice issued under Section 18 of the Legal Metrology Act, 2009.",
  },
  {
    id: "INS-2026-0840",
    productName: "Organic Multi-Flora Honey 250g",
    brandName: "PureHimalaya Apiculture",
    category: "Food & Beverages",
    batchNumber: "PH-HNY-102",
    inspectorId: "usr-04",
    inspectorName: "Amitabh Verma",
    inspectorEmail: "amitabh.verma@lm.gov.in",
    status: "NEEDS_REVIEW",
    complianceScore: 74,
    violationsCount: 1,
    scannedAt: "2026-09-15 17:15:30",
    hashSha256: "c157a79031e1c40f85931829bc5fc552add14b1460ee74c5b30266149f3c8797",
    qrVerified: true,
    findings: [
      {
        id: "f-06",
        ruleCode: "C04",
        field: "Manufacturing Date",
        status: "FLAGGED",
        detectedValue: "MFG: 08/??/26 (Partially Smudged)",
        confidenceScore: 0.62,
        severity: "HIGH",
        legalRef: "Rule 6(1)(d), PCR 2011",
        officerRemarks: "Inkjet lot stamp blurred. Pending field officer re-inspection with high magnification.",
      },
    ],
    notes: "OCR confidence low due to curved glass reflection. Scheduled for physical inspection verification.",
  },
  {
    id: "INS-2026-0839",
    productName: "Instant Masala Noodles 70g",
    brandName: "QuickBite Foods",
    category: "Packaged Food",
    batchNumber: "QB-NDL-504",
    inspectorId: "usr-02",
    inspectorName: "Rajesh Sharma",
    inspectorEmail: "rajesh.sharma@lm.gov.in",
    status: "COMPLIANT",
    complianceScore: 100,
    violationsCount: 0,
    scannedAt: "2026-09-15 14:10:00",
    reviewedAt: "2026-09-15 14:12:30",
    hashSha256: "1b4f0e985197199f8da0924b56ad2ced47f7da3ab5d1a94259d309fa08b15631",
    qrVerified: true,
    findings: [
      {
        id: "f-07",
        ruleCode: "C01",
        field: "MRP",
        status: "PASS",
        detectedValue: "₹ 14.00 (Incl. of all taxes)",
        confidenceScore: 0.99,
        severity: "CRITICAL",
        legalRef: "Rule 6(1)(e)",
      },
    ],
  },
  {
    id: "INS-2026-0838",
    productName: "Copper Bottom Stainless Steel Kadhai 24cm",
    brandName: "Kuber Kitchenware",
    category: "Cookware & Utensils",
    batchNumber: "KB-KD-24",
    inspectorId: "usr-05",
    inspectorName: "Kavita Nair",
    inspectorEmail: "kavita.nair@lm.gov.in",
    status: "NON_COMPLIANT",
    complianceScore: 50,
    violationsCount: 2,
    scannedAt: "2026-09-14 11:45:00",
    reviewedAt: "2026-09-14 11:52:00",
    hashSha256: "2c624232cdd221771294dfbb310aca000a0df6ec8b6602f745406fb7d4f33d45",
    qrVerified: true,
    findings: [
      {
        id: "f-08",
        ruleCode: "C02",
        field: "Dimension & Size",
        status: "FAIL",
        detectedValue: "Size 24",
        confidenceScore: 0.95,
        severity: "HIGH",
        legalRef: "PCR 2011 Schedule 2",
        officerRemarks: "Did not specify unit of measurement ('cm' or 'mm').",
      },
      {
        id: "f-09",
        ruleCode: "C03",
        field: "Customer Helpline",
        status: "FAIL",
        detectedValue: "NOT DETECTED",
        confidenceScore: 0.98,
        severity: "HIGH",
        legalRef: "Rule 6(1)(g)",
        officerRemarks: "Completely missing customer care contact details on outer package wrapper.",
      },
    ],
  },
];

export async function getSystemInspections(): Promise<SystemInspection[]> {
  return [...MOCK_INSPECTIONS];
}

export async function getSystemInspectionById(id: string): Promise<SystemInspection | null> {
  const item = MOCK_INSPECTIONS.find((i) => i.id === id);
  return item ? { ...item } : null;
}

export function exportInspectionsCsv(inspections: SystemInspection[]): string {
  const headers = [
    "Inspection ID",
    "Product Name",
    "Brand",
    "Category",
    "Inspector Name",
    "Status",
    "Compliance Score",
    "Violations Count",
    "Scanned At",
    "SHA-256 Hash",
  ];

  const rows = inspections.map((i) => [
    i.id,
    `"${i.productName.replace(/"/g, '""')}"`,
    `"${i.brandName.replace(/"/g, '""')}"`,
    `"${i.category}"`,
    `"${i.inspectorName}"`,
    i.status,
    i.complianceScore,
    i.violationsCount,
    `"${i.scannedAt}"`,
    i.hashSha256,
  ]);

  return [headers.join(","), ...rows.map((r) => r.join(","))].join("\n");
}
